# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='url',
            new_name='slug',
        ),
    ]
